import React from 'react';

function Language() {
    return (
        <div className='col-5 d-flex align-items-center'>
            <label className='col-3'>
                Language
            </label>
            <select className="form-select filter-entry" id="language" name="language">
                <option value="Ady">Adyghe</option>
                <option value="Aar">Afar</option>
                <option value="Sqi">Albanian</option>
                <option value="Amh">Amharic</option>
                <option value="Ara">Arabic</option>
                <option value="Aae">Arbëreshë Albanian</option>
                <option value="Hye">Armenian</option>
                <option value="Csh">Asho Chin</option>
                <option value="Asm">Assamese</option>
                <option value="Aze">Azerbaijani</option>
                <option value="Ban">Balinese</option>
                <option value="Bal">Baluchi</option>
                <option value="Bam">Bambara</option>
                <option value="Bel">Belarusian</option>
                <option value="Ben">Bengali</option>
                <option value="Bgw">Bhatri</option>
                <option value="Bis">Bislama</option>
                <option value="Bos">Bosnian</option>
                <option value="Bul">Bulgarian</option>
                <option value="Mya">Burmese</option>
                <option value="Yue">Cantonese</option>
                <option value="Khm">Central Khmer</option>
                <option value="Pst">Central Pashto</option>
                <option value="Zho">Chinese</option>
                <option value="Hrv">Croatian</option>
                <option value="Ces">Czech</option>
                <option value="Prs">Dari</option>
                <option value="Dso">Desiya</option>
                <option value="Nld">Dutch</option>
                <option value="Dyu">Dyula</option>
                <option value="Dzo">Dzongkha</option>
                <option selected="" value="Eng">English</option>
                <option value="Epo">Esperanto</option>
                <option value="Fil">Filipino</option>
                <option value="Fra">French</option>
                <option value="Ful">Fulah</option>
                <option value="Kat">Georgian</option>
                <option value="Deu">German</option>
                <option value="Guj">Gujarati</option>
                <option value="Hak">Hakka Chinese</option>
                <option value="Hau">Hausa</option>
                <option value="Haz">Hazaragi</option>
                <option value="Heb">Hebrew</option>
                <option value="Hin">Hindi</option>
                <option value="Hmn">Hmong</option>
                <option value="Var">Huarijio</option>
                <option value="Hun">Hungarian</option>
                <option value="Ibo">Igbo</option>
                <option value="Ilo">Iloko</option>
                <option value="Ind">Indonesian</option>
                <option value="Ita">Italian</option>
                <option value="Ium">Iu Mien</option>
                <option value="Jpn">Japanese</option>
                <option value="Jav">Javanese</option>
                <option value="Kac">Kachin</option>
                <option value="Kan">Kannada</option>
                <option value="Kau">Kanuri</option>
                <option value="Kaz">Kazakh</option>
                <option value="Khg">Khams Tibetan</option>
                <option value="Kha">Khasi</option>
                <option value="Kjg">Khmu</option>
                <option value="Kin">Kinyarwanda</option>
                <option value="Kir">Kirghiz</option>
                <option value="Trp">Kok Borok</option>
                <option value="Kor">Korean</option>
                <option value="Kun">Kunama</option>
                <option value="Kur">Kurdish</option>
                <option value="Lhu">Lahu</option>
                <option value="Lao">Lao</option>
                <option value="Lat">Latin</option>
                <option value="Lis">Lisu</option>
                <option value="Lom">Loma (Liberia)</option>
                <option value="Lus">Lushai</option>
                <option value="Khb">Lü</option>
                <option value="Rup">Macedo Romanian</option>
                <option value="Mad">Madurese</option>
                <option value="Vmw">Makhuwa</option>
                <option value="Mlg">Malagasy</option>
                <option value="Mly">Malay (individual language)</option>
                <option value="Msa">Malay (macrolanguage)</option>
                <option value="Mal">Malayalam</option>
                <option value="Cmn">Mandarin Chinese</option>
                <option value="Man">Mandingo</option>
                <option value="Mni">Manipuri</option>
                <option value="Kxf">Manumanaw Karen</option>
                <option value="Mar">Marathi</option>
                <option value="Mas">Masai</option>
                <option value="Axm">Middle Armenian</option>
                <option value="Nan">Min Nan Chinese</option>
                <option value="Min">Minangkabau</option>
                <option value="Ell">Modern Greek (1453-)</option>
                <option value="Mnw">Mon</option>
                <option value="Mon">Mongolian</option>
                <option value="Mos">Mossi</option>
                <option value="Mul">Multiple languages</option>
                <option value="Nep">Nepali</option>
                <option value="Nij">Ngaju</option>
                <option value="Pcm">Nigerian Pidgin</option>
                <option value="Tts">Northeastern Thai</option>
                <option value="Nor">Norwegian</option>
                <option value="Ori">Oriya</option>
                <option value="Oro">Orokolo</option>
                <option value="Orm">Oromo</option>
                <option value="Pan">Panjabi</option>
                <option value="Mvf">Peripheral Mongolian</option>
                <option value="Fas">Persian</option>
                <option value="Pol">Polish</option>
                <option value="Por">Portuguese</option>
                <option value="Pus">Pushto</option>
                <option value="Ron">Romanian</option>
                <option value="Rus">Russian</option>
                <option value="Ksw">S'gaw Karen</option>
                <option value="Srp">Serbian</option>
                <option value="Shn">Shan</option>
                <option value="Sna">Shona</option>
                <option value="Iii">Sichuan Yi</option>
                <option value="Sid">Sidamo</option>
                <option value="Xst">Silt'e</option>
                <option value="Snd">Sindhi</option>
                <option value="Sin">Sinhala</option>
                <option value="Som">Somali</option>
                <option value="Spa">Spanish</option>
                <option value="Arb">Standard Arabic</option>
                <option value="Chn">Standart Chinese</option>
                <option value="Apd">Sudanese Arabic</option>
                <option value="Sun">Sundanese</option>
                <option value="Swa">Swahili (macrolanguage)</option>
                <option value="Shi">Tachelhit</option>
                <option value="Tgl">Tagalog</option>
                <option value="Tgk">Tajik</option>
                <option value="Tam">Tamil</option>
                <option value="Tat">Tatar</option>
                <option value="Tel">Telugu</option>
                <option value="Tha">Thai</option>
                <option value="Bod">Tibetan</option>
                <option value="Tir">Tigrinya</option>
                <option value="Tur">Turkish</option>
                <option value="Tuk">Turkmen</option>
                <option value="Twi">Twi</option>
                <option value="Aoz">Uab Meto</option>
                <option value="Uig">Uighur</option>
                <option value="Ukr">Ukrainian</option>
                <option value="Umb">Umbundu</option>
                <option value="Und">Undetermined</option>
                <option value="Urd">Urdu</option>
                <option value="Uzb">Uzbek</option>
                <option value="Vie">Vietnamese</option>
                <option value="Jub">Wannu</option>
                <option value="Pes">Western Farsi</option>
                <option value="Yao">Yao</option>
                <option value="Yor">Yoruba</option>
            </select>
        </div>
    );
}

export default Language;